### ISSUE TITLE
pip install vprof installs 0.22 instead of 0.3

### ISSUE THREAD

**Issue by nvdv** [nvdv/vprof#38]
At present ```pip install vprof``` installs v0.22 instead of latest v0.3.
Current workaround: ```pip install vprof==0.3```

**Comment by onyb** [comment]
Looks like the version numbering system is the culprit. Package [info](https://pypi.python.org/pypi/vprof/json) shows that `v0.22` is the latest version. I guess you wanted `v0.2.2` instead of `v0.22`. You can read PEP 440 to get an idea about version numbering best practices.

The only solution I can think of is to delete `v0.22` and re-upload it as `v0.2.2` (assuming it is possible).

**Comment by tshirtman** [comment]
or rename 0.3 to 0.30 if easier :)

**Comment by nvdv** [comment]
I renamed 0.3 to 0.30 and it seems that issue is fixed now.
